name: brt
channels:
  - pytorch
  - dglteam/label/cu121
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - defaults
dependencies:
  - dgl=2.1.0.cu121
  - python=3.10.8
  - pythonocc-core
  - pytorch=2.2.1
  - pytorch-cuda=12.1
  - matplotlib
  - pip:
      - geomdl==5.3.1
      - numpy==1.23.5
      - pytorch-lightning==2.2.4
      - scikit-learn==1.4.2
      - scipy==1.14.1
      - tensorboard==2.16.2
